SET IDENTITY_INSERT [dbo].[Teams] ON
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (1, N'OG', N'http://ogs.gg')
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (2, N'Team Liquid ', N'http://www.teamliquid.net')
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (3, N'PSG.LGD', NULL)
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (4, N'Team Secret', N'http://www.teamsecret.gg')
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (5, N'Evil Geniuses', N'http://www.evilgeniuses.net')
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (6, N'Vici Gaming', N'http://www.vicigaming.com')
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (7, N'Royal Never Give Up', NULL)
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (8, N'Infamous', N'http://www.infamous.gg/')
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (9, N'TNC Predator', N'http://www.tncproteam.com/')
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (10, N'Virtus.pro', N'http://virtus.pro')
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (11, N'Newbee.TI9', NULL)
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (12, N'Mineski', N'http://www.mineski.net')
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (13, N'Fnatic', N'http://www.fnatic.com')
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (14, N'Keen Gaming', NULL)
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (15, N'Natus Vincere', N'http://navi.gg/')
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (16, N'Alliance', N'http://www.thealliance.gg')
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (17, N'Chaos', N'http://digitalchaos.gg')
INSERT INTO [dbo].[Teams] ([Id], [Name], [Url]) VALUES (18, N'Ninjas in Pyjamas', N'http://www.nip-gaming.se')
SET IDENTITY_INSERT [dbo].[Teams] OFF
