SET IDENTITY_INSERT [dbo].[Countries] ON
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (1, N'Пакистан')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (2, N'Финляндия')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (3, N'США')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (4, N'Македония')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (5, N'Дания')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (6, N'Австралия')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (7, N'Швеция')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (8, N'Германия')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (9, N'Норвегия')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (10, N'Китай')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (11, N'Малайзия')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (12, N'Польша')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (13, N'Иордания')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (14, N'Эстония')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (15, N'Канада')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (16, N'Филиппины')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (17, N'Россия')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (18, N'Израиль')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (19, N'Перу')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (20, N'Колумбия')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (21, N'Аргентина')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (22, N'Южная Корея')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (23, N'Австралия')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (24, N'Украина')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (25, N'Кыргызстан')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (26, N'Таиланд')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (27, N'Сингапур')
INSERT INTO [dbo].[Countries] ([Id], [CountryName]) VALUES (28, N'Чехия')
SET IDENTITY_INSERT [dbo].[Countries] OFF
